<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Персональная страница");
?><?$APPLICATION->IncludeComponent("bitrix:catalog.section", ".default", array(
                                                               "IBLOCK_TYPE"                     => "medservices",
                                                               "IBLOCK_ID"                       => "#SERVICES_BLOCK_ID#",
                                                               "SECTION_ID"                      => $_REQUEST["SECTION_ID"],
                                                               "SECTION_CODE"                    => "",
                                                               "ELEMENT_SORT_FIELD"              => "GROUPS",
                                                               "ELEMENT_SORT_ORDER"              => "asc",
                                                               "FILTER_NAME"                     => "arrFilter",
                                                               "INCLUDE_SUBSECTIONS"             => "Y",
                                                               "SHOW_ALL_WO_SECTION"             => "N",
                                                               "PAGE_ELEMENT_COUNT"              => "50",
                                                               "LINE_ELEMENT_COUNT"              => "1",
                                                               "PROPERTY_CODE"                   => array(
                                                                   0 => "",
                                                                   1 => "GROUPS",
                                                               ),
                                                               "SECTION_URL"                     => "",
                                                               "DETAIL_URL"                      => "",
                                                               "BASKET_URL"                      => "/personal/basket.php",
                                                               "ACTION_VARIABLE"                 => "action",
                                                               "PRODUCT_ID_VARIABLE"             => "id",
                                                               "PRODUCT_QUANTITY_VARIABLE"       => "quantity",
                                                               "PRODUCT_PROPS_VARIABLE"          => "prop",
                                                               "SECTION_ID_VARIABLE"             => "SECTION_ID",
                                                               "AJAX_MODE"                       => "Y",
                                                               "AJAX_OPTION_SHADOW"              => "Y",
                                                               "AJAX_OPTION_JUMP"                => "N",
                                                               "AJAX_OPTION_STYLE"               => "Y",
                                                               "AJAX_OPTION_HISTORY"             => "N",
                                                               "CACHE_TYPE"                      => "A",
                                                               "CACHE_TIME"                      => "3600",
                                                               "CACHE_GROUPS"                    => "Y",
                                                               "META_KEYWORDS"                   => "-",
                                                               "META_DESCRIPTION"                => "-",
                                                               "BROWSER_TITLE"                   => "-",
                                                               "ADD_SECTIONS_CHAIN"              => "N",
                                                               "DISPLAY_COMPARE"                 => "N",
                                                               "SET_TITLE"                       => "Y",
                                                               "SET_STATUS_404"                  => "N",
                                                               "CACHE_FILTER"                    => "N",
                                                               "PRICE_CODE"                      => "",
                                                               "USE_PRICE_COUNT"                 => "N",
                                                               "SHOW_PRICE_COUNT"                => "1",
                                                               "PRICE_VAT_INCLUDE"               => "N",
                                                               "PRODUCT_PROPERTIES"              => "",
                                                               "USE_PRODUCT_QUANTITY"            => "N",
                                                               "DISPLAY_TOP_PAGER"               => "N",
                                                               "DISPLAY_BOTTOM_PAGER"            => "Y",
                                                               "PAGER_TITLE"                     => "Eckeub",
                                                               "PAGER_SHOW_ALWAYS"               => "N",
                                                               "PAGER_TEMPLATE"                  => "",
                                                               "PAGER_DESC_NUMBERING"            => "N",
                                                               "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
                                                               "PAGER_SHOW_ALL"                  => "Y",
                                                               "AJAX_OPTION_ADDITIONAL"          => ""
                                                           ),
                                   false,
                                   array(
                                       "ACTIVE_COMPONENT" => "N"
                                   )
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>