<?
define("NEED_AUTH", true);
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Мои обращения");
?>

<?$APPLICATION->IncludeComponent(
	"bitrix:news",
	"personal_feedback",
	Array(
		"DISPLAY_DATE"                    => "Y",
		"DISPLAY_PICTURE"                 => "Y",
		"DISPLAY_PREVIEW_TEXT"            => "Y",
		"USE_SHARE"                       => "N",
		"SEF_MODE"                        => "Y",
		"SEF_FOLDER"                      => "/personal/requests/",
		"AJAX_MODE"                       => "N",
		"IBLOCK_TYPE" => "registry",
		"IBLOCK_ID" => "16",
		"NEWS_COUNT"                      => "20",
		"USE_SEARCH"                      => "N",
		"USE_RSS"                         => "Y",
		"USE_RATING"                      => "N",
		"USE_CATEGORIES"                  => "N",
		"USE_REVIEW"                      => "N",
		"USE_FILTER" => "Y",
		"FILTER_NAME" => "arrFilter",
		"SORT_BY1"                        => "ACTIVE_FROM",
		"SORT_ORDER1"                     => "DESC",
		"SORT_BY2"                        => "SORT",
		"SORT_ORDER2"                     => "ASC",
		"CHECK_DATES"                     => "Y",
		"PREVIEW_TRUNCATE_LEN"            => "",
		"LIST_ACTIVE_DATE_FORMAT"         => "d.m.Y",
		"LIST_FIELD_CODE"                 => array(
		0 => "PREVIEW_TEXT",
		1 => "DATE_ACTIVE_TO",
		2 => "ACTIVE_TO",
		3 => "",
		),
		"LIST_PROPERTY_CODE"              => array(
		0 => "STATUS",
		1 => "",
		),
		"HIDE_LINK_WHEN_NO_DETAIL"        => "N",
		"DISPLAY_NAME"                    => "N",
		"META_KEYWORDS"                   => "-",
		"META_DESCRIPTION"                => "-",
		"BROWSER_TITLE"                   => "-",
		"DETAIL_ACTIVE_DATE_FORMAT"       => "d.m.Y",
		"DETAIL_FIELD_CODE"               => array(),
		"DETAIL_PROPERTY_CODE"            => array(
		0 => "STATUS",
		1 => "",
		),
		"DETAIL_DISPLAY_TOP_PAGER"        => "N",
		"DETAIL_DISPLAY_BOTTOM_PAGER"     => "Y",
		"DETAIL_PAGER_TITLE"              => "Страница",
		"DETAIL_PAGER_TEMPLATE"           => "",
		"DETAIL_PAGER_SHOW_ALL"           => "N",
		"SET_TITLE"                       => "N",
		"SET_STATUS_404"                  => "N",
		"INCLUDE_IBLOCK_INTO_CHAIN"       => "Т",
		"ADD_SECTIONS_CHAIN"              => "Т",
		"USE_PERMISSIONS"                 => "N",
		"CACHE_TYPE"                      => "A",
		"CACHE_TIME"                      => "3600",
		"CACHE_NOTES"                     => "",
		"CACHE_FILTER"                    => "N",
		"CACHE_GROUPS"                    => "Y",
		"DISPLAY_TOP_PAGER"               => "N",
		"DISPLAY_BOTTOM_PAGER"            => "Y",
		"PAGER_TITLE"                     => "Обращения",
		"PAGER_SHOW_ALWAYS"               => "N",
		"PAGER_TEMPLATE"                  => "",
		"PAGER_DESC_NUMBERING"            => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL"                  => "N",
		"VARIABLE_ALIASES"                => Array(
			"SECTION_ID" => "SECTION_ID",
			"ELEMENT_ID" => "ID"
		),
		"AJAX_OPTION_SHADOW"              => "Y",
		"AJAX_OPTION_JUMP"                => "N",
		"AJAX_OPTION_STYLE"               => "Y",
		"AJAX_OPTION_HISTORY"             => "N",
		"AJAX_OPTION_ADDITIONAL"          => "",
		"SEF_URL_TEMPLATES"               => array(
			"news"    => "",
			"section" => "",
			"detail"  => "#ELEMENT_ID#/",
		)
	),
	false
);?>
	<br><br>
<?$APPLICATION->IncludeComponent("bitrix:iblock.element.add.form", "clinic_statement", array(
		"IBLOCK_TYPE"                   => "registry",
		"IBLOCK_ID"                     => "16",
		"STATUS_NEW"                    => "N",
		"LIST_URL"                      => "",
		"USE_CAPTCHA"                   => "N",
		"USER_MESSAGE_EDIT"             => "",
		"USER_MESSAGE_ADD"              => "Спасибо, ваш вопрос добавлен",
		"DEFAULT_INPUT_SIZE"            => "50",
		"RESIZE_IMAGES"                 => "N",
		"PROPERTY_CODES"                => array(
			0 => "NAME",
			1 => "DATE_ACTIVE_FROM",
			2 => "DATE_ACTIVE_TO",
			3 => "PREVIEW_TEXT",
			4 => "32",
			5 => "31",
		),
		"PROPERTY_CODES_REQUIRED"       => array(
			0 => "NAME",
			1 => "PREVIEW_TEXT",
			2 => "32",
		),
		"GROUPS"                        => array(
			0 => "2",
		),
		"STATUS"                        => "ANY",
		"ELEMENT_ASSOC"                 => "CREATED_BY",
		"MAX_USER_ENTRIES"              => "100000",
		"MAX_LEVELS"                    => "100000",
		"LEVEL_LAST"                    => "Y",
		"MAX_FILE_SIZE"                 => "0",
		"PREVIEW_TEXT_USE_HTML_EDITOR"  => "N",
		"DETAIL_TEXT_USE_HTML_EDITOR"   => "N",
		"SEF_MODE"                      => "N",
		"SEF_FOLDER"                    => "/personal/",
		"CUSTOM_TITLE_NAME"             => "ФИО",
		"CUSTOM_TITLE_TAGS"             => "",
		"CUSTOM_TITLE_DATE_ACTIVE_FROM" => "",
		"CUSTOM_TITLE_DATE_ACTIVE_TO"   => "",
		"CUSTOM_TITLE_IBLOCK_SECTION"   => "",
		"CUSTOM_TITLE_PREVIEW_TEXT"     => "Ваш вопрос",
		"CUSTOM_TITLE_PREVIEW_PICTURE"  => "",
		"CUSTOM_TITLE_DETAIL_TEXT"      => "",
		"CUSTOM_TITLE_DETAIL_PICTURE"   => "",
		"FIELDS_ORDER"                  => array(
			0 => "NAME",
			1 => "32",
			2 => "31",
			3 => "PREVIEW_TEXT",
			4 => "",
		)
	),
	false
);?>

<? require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php"); ?>