<?
$arUrlRewrite = array(
	array(
		"CONDITION" => "#^/for_staff/hospitalization_list/([0-9]+)/([0-9]+)/(.*)#",
		"RULE" => "SECTION_ID=\$1&ID=\$2",
		"ID" => "",
		"PATH" => "/for_staff/hospitalization_list.php",
	),
	array(
		"CONDITION" => "#^/for_staff/view_hospitalization_claim/([0-9]+)/(.*)#",
		"RULE" => "RESULT_ID=\$1",
		"ID" => "",
		"PATH" => "/for_staff/view_hospitalization_claim.php",
	),
	array(
		"CONDITION" => "#^/for_staff/edit_hospitalization_claim/([0-9]+)/(.*)#",
		"RULE" => "RESULT_ID=\$1",
		"ID" => "",
		"PATH" => "/for_staff/edit_hospitalization_claim.php",
	),
	array(
		"CONDITION" => "#^/services/price_list/package_price/([0-9]+)/(.*)#",
		"RULE" => "package=\$1",
		"ID" => "",
		"PATH" => "/services/price_list/package_price.php",
	),
	array(
		"CONDITION" => "#^/for_staff/view_clinic_statement/([0-9]+)/(.*)#",
		"RULE" => "RESULT_ID=\$1",
		"ID" => "",
		"PATH" => "/for_staff/view_clinic_statement.php",
	),
	array(
		"CONDITION" => "#^/for_staff/edit_clinic_statement/([0-9]+)/(.*)#",
		"RULE" => "RESULT_ID=\$1",
		"ID" => "",
		"PATH" => "/for_staff/edit_clinic_statement.php",
	),
	array(
		"CONDITION" => "#^/for_staff/hospitalization_list/([0-9]+)/(.*)#",
		"RULE" => "SECTION_ID=\$1",
		"ID" => "",
		"PATH" => "/for_staff/hospitalization_list.php",
	),
	array(
		"CONDITION" => "#^/for_staff/edit_hospitalization_claim/#",
		"RULE" => "",
		"ID" => "medsite:form.result.edit",
		"PATH" => "/for_staff/edit_hospitalization_claim.php",
	),
	array(
		"CONDITION" => "#^/for_staff/view_hospitalization_claim/#",
		"RULE" => "",
		"ID" => "medsite:form.result.view",
		"PATH" => "/for_staff/view_hospitalization_claim.php",
	),
	array(
		"CONDITION" => "#^/contacts/organization/([0-9]+)/(.*)#",
		"RULE" => "ELEMENT_ID=\$1",
		"ID" => "",
		"PATH" => "/contacts/organization.php",
	),
	array(
		"CONDITION" => "#^/for_staff/view_clinic_statement/#",
		"RULE" => "",
		"ID" => "bitrix:form.result.view",
		"PATH" => "/for_staff/view_clinic_statement.php",
	),
	array(
		"CONDITION" => "#^/for_staff/edit_clinic_statement/#",
		"RULE" => "",
		"ID" => "bitrix:form.result.edit",
		"PATH" => "/for_staff/edit_clinic_statement.php",
	),
	array(
		"CONDITION" => "#^/for_staff/hospitalization_list/#",
		"RULE" => "",
		"ID" => "",
		"PATH" => "/for_staff/hospitalization_list.php",
	),
	array(
		"CONDITION" => "#^/mobile_app/personal/requests/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/mobile_app/personal/requests/index.php",
	),
	array(
		"CONDITION" => "#^/personal/insurance-companies/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/personal/insurance-companies/index.php",
	),
	array(
		"CONDITION" => "#^/for_staff/analysis_results/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "//for_staff/analysis_results.php",
	),
	array(
		"CONDITION" => "#^/services/recomendations/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/services/recomendations/index.php",
	),
	array(
		"CONDITION" => "#^/bitrix/services/ymarket/#",
		"RULE" => "",
		"ID" => "",
		"PATH" => "/bitrix/services/ymarket/index.php",
	),
	array(
		"CONDITION" => "#^/services/price_list/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/services/price_list/index.php",
	),
	array(
		"CONDITION" => "#^/m/personal/requests/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/m/personal/requests/index.php",
	),
	array(
		"CONDITION" => "#^/mobile_app/services/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/mobile_app/services/index.php",
	),
	array(
		"CONDITION" => "#^/personal/requests/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/personal/requests/index.php",
	),
	array(
		"CONDITION" => "#^/personal/analysis/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/personal/analysis/index.php",
	),
	array(
		"CONDITION" => "#^/mobile_app/advert/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/mobile_app/advert/index.php",
	),
	array(
		"CONDITION" => "#^/mobile_app/news/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/mobile_app/news/index.php",
	),
	array(
		"CONDITION" => "#^/personal/order/#",
		"RULE" => "",
		"ID" => "bitrix:sale.personal.order",
		"PATH" => "/personal/order/index.php",
	),
	array(
		"CONDITION" => "#^/about/gallery/#",
		"RULE" => "",
		"ID" => "bitrix:photogallery",
		"PATH" => "/about/gallery/index.php",
	),
	array(
		"CONDITION" => "#^/about/advert/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/about/advert/index.php",
	),
	array(
		"CONDITION" => "#^/about/forum/#",
		"RULE" => "",
		"ID" => "bitrix:forum",
		"PATH" => "/about/forum/index.php",
	),
	array(
		"CONDITION" => "#^/about/news/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/about/news/index.php",
	),
	array(
		"CONDITION" => "#^/about/jobs/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/about/jobs/index.php",
	),
	array(
		"CONDITION" => "#^/m/services/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/m/services/index.php",
	),
	array(
		"CONDITION" => "#^/about/blog/#",
		"RULE" => "",
		"ID" => "bitrix:blog",
		"PATH" => "/about/blog/index.php",
	),
	array(
		"CONDITION" => "#^/m/advert/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/m/advert/index.php",
	),
	array(
		"CONDITION" => "#^/m/news/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/m/news/index.php",
	),
);

?>