<?
$aMenuLinks = Array(
    Array(
        "О клинике",
        "/about/index.php",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Структура клиники",
        "/about/structure.php",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Объявления",
        "/about/advert/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Медицинские новости",
        "/about/news/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Вакансии",
        "/about/jobs/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Лицензии",
        "/about/license.php",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Фотогалерея",
        "/about/gallery/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Блог",
        "/about/blog/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Форум",
        "/about/forum/",
        Array(),
        Array(),
        ""
    ),
);
?>